name: CI/CD for Playwright, Robot Framework, and Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js for Cypress and Playwright
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Set up Python for Robot Framework
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.12'

      - name: Install Python dependencies for Robot Framework
        run: |
          # Install Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt --fix-broken install -y  # Install any missing dependencies

          # Install ChromeDriver
          LATEST_CHROMEDRIVER=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          pip3 install -r requirements.txt

  cypress_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js for Cypress
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Install Cypress dependencies
        run: |
          cd Cypress
          npm install

      - name: Run Cypress tests
        run: |
          cd Cypress
          npx cypress run

  playwright_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js for Playwright
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Install Playwright dependencies
        run: |
          cd Playwright
          npm install

      - name: Install Playwright browsers
        run: |
          cd Playwright
          npx playwright install

      - name: Run Playwright tests
        run: |
          cd Playwright
          npx playwright test  # or npx playwright test

  robotframework_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Robot Framework tests
        run: |
          cd Robotframework
          robot -d Logs Testcases  # This assumes you have robot framework tests in 'robotframework/tests'
