name: CI/CD for Playwright, Robot Framework, and Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js for Cypress and Playwright
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Set up Python for Robot Framework
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.12'

      - name: Install Python dependencies for Robot Framework
        run: |
          apt-get update && apt-get -y install gnupg2 wget python3-tk tk-dev unzip ca-certificates libpq-dev git
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
          && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
          apt-get update && apt-get -y install google-chrome-stable
          CHROMEDRIVER_VERSION=`wget --no-verbose --output-document - https://chromedriver.storage.googleapis.com/LATEST_RELEASE` && wget --no-verbose --output-document /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip -qq /tmp/chromedriver_linux64.zip -d /usr/bin/chromedriver
          PATH="${PATH}:/usr/bin/chromedriver"
          chmod 777 /usr/bin/chromedriver
          wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip -O browserstack-local-linux.zip
          python3 -m pip install loguru
          python3 -m pip install pyyaml
          pip3 install -r requirements.txt

  cypress_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js for Cypress
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Install Cypress dependencies
        run: |
          cd Cypress
          npm install

      - name: Run Cypress tests
        run: |
          cd Cypress
          npx cypress run

  playwright_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js for Playwright
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Install Playwright dependencies
        run: |
          cd Playwright
          npm install

      - name: Install Playwright browsers
        run: |
          cd Playwright
          npx playwright install

      - name: Run Playwright tests
        run: |
          cd Playwright
          npx playwright test  # or npx playwright test

  robotframework_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Robot Framework tests
        run: |
          cd Robotframework
          robot -d Logs Testcases  # This assumes you have robot framework tests in 'robotframework/tests'
