name: Automation Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Change to your required Node version

      - name: Install Node dependencies
        run: npm install

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Change to your desired Python version

      - name: Install Python dependencies
        run: pip install -r requirements.txt  # Ensure robotframework dependencies are listed

  playwright_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npm test  # Assuming your Playwright tests are executed via npm test

  robotframework_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt  # Make sure to install Robot Framework dependencies

      - name: Run Robot Framework tests
        run: robot tests  # Assuming you have a "tests" directory with robot tests

  cypress_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run  # This runs Cypress tests

